export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
  DEV = 'DEV',
}

export enum SyncStatus {
  PENDING = 'PENDING',
  SYNCED_CLIENT = 'SYNCED_CLIENT',
  SYNCED = 'SYNCED',
  SAVED = 'SAVED',
  ERROR = 'ERROR',
  DELETED = 'DELETED',
}

export enum Priority {
  URGENT_IMPORTANT = 'URGENT_IMPORTANT',
  NOT_URGENT_IMPORTANT = 'NOT_URGENT_IMPORTANT',
  URGENT_UNIMPORTANT = 'URGENT_UNIMPORTANT',
  NOT_URGENT_UNIMPORTANT = 'NOT_URGENT_UNIMPORTANT',
}

export enum Frequency {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  SEMI_ANNUALLY = 'SEMI_ANNUALLY',
  ANNUALLY = 'ANNUALLY',
}
